name       : supertuxkart
version    : '1.2'
release    : 13
source     :
    - https://iweb.dl.sourceforge.net/project/supertuxkart/SuperTuxKart/1.2/SuperTuxKart-1.2-src.tar.xz : 052edf0afdbeb99583fe8676fb0ab80ecb6103fb88b7540f858d1b5fa1297d37
license    :
    - GPL-3.0-or-later
    - CC-BY-SA-3.0
component  : games.arcade
summary    : SuperTuxKart is a Free 3D kart racing game, with many tracks, characters and items for you to try
description: |
    SuperTuxKart is a 3D open-source arcade racer with a variety characters, tracks, and modes to play.
patterns   :
    - assets : /usr/share/supertuxkart
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - pkgconfig(xrandr)
    - libopenglrecorder-devel
    - wiiuse-devel
    - cantarell-fonts
rundeps    :
    - cantarell-fonts
    - supertuxkart-assets
setup      : |
    %patch -p1 < $pkgfiles/Fix-build-with-latest-SDL2.patch

    %cmake_ninja -DUSE_SYSTEM_WIIUSE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    rm $installdir/usr/share/supertuxkart/data/ttf/Cantarell-Regular.otf
    ln -s /usr/share/fonts/opentype/cantarell/Cantarell-Regular.otf $installdir/usr/share/supertuxkart/data/ttf/Cantarell-Regular.otf
