name       : supertuxkart
version    : '1.4'
release    : 17
source     :
    - https://github.com/supertuxkart/stk-code/releases/download/1.4/SuperTuxKart-1.4-src.tar.xz : 9890392419baf4715313f14d5ad60746f276eed36eb580636caf44e2532c0f03
homepage   : https://supertuxkart.net/
license    :
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
component  :
    - games.arcade
    - assets : games.arcade
summary    : SuperTuxKart is a Free 3D kart racing game, with many tracks, characters and items for you to try
description: |
    SuperTuxKart is a 3D open-source arcade racer with a variety characters, tracks, and modes to play.
patterns   :
    - assets : /usr/share/supertuxkart
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - pkgconfig(xrandr)
    - libopenglrecorder-devel
    - wiiuse-devel
    - cantarell-fonts
rundeps    :
    - cantarell-fonts
    - supertuxkart-assets
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-install-angelscript-devel-files.patch
    %cmake_ninja -DUSE_SYSTEM_WIIUSE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    rm $installdir/usr/share/supertuxkart/data/ttf/Cantarell-Regular.otf
    ln -s /usr/share/fonts/opentype/cantarell/Cantarell-Regular.otf $installdir/usr/share/supertuxkart/data/ttf/Cantarell-Regular.otf
