name       : supertuxkart
version    : '1.1'
release    : 8
source     :
    - https://iweb.dl.sourceforge.net/project/supertuxkart/SuperTuxKart/1.1/supertuxkart-1.1-src.tar.xz : e9b02b0b11ab68aacaec38306903feffe59a501224805cd3645cebf10e880ae8
license    :
    - GPL-3.0-or-later
    - CC-BY-SA-3.0
component  : games.arcade
summary    : SuperTuxKart is a Free 3D kart racing game, with many tracks, characters and items for you to try
description: |
    SuperTuxKart is a 3D open-source arcade racer with a variety characters, tracks, and modes to play.
patterns   :
    - assets : /usr/share/supertuxkart
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(glu)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - pkgconfig(xrandr)
    - libopenglrecorder-devel
    - wiiuse-devel
    - cantarell-fonts
rundeps    :
    - cantarell-fonts
    - supertuxkart-assets
setup      : |
    %cmake_ninja -DUSE_SYSTEM_WIIUSE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    rm $installdir/usr/share/supertuxkart/data/ttf/Cantarell-Regular.otf
    ln -s /usr/share/fonts/cantarell/Cantarell-Regular.otf $installdir/usr/share/supertuxkart/data/ttf/Cantarell-Regular.otf
