name       : supertuxkart
version    : 0.9.1
release    : 1
source     :
    - http://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.1/supertuxkart-0.9.1-src.tar.xz : c50f00a71df165fb613d20e86bea2d9d5e51ed3e27e1d436fbac3b07cf2ea149
license    :
    - GPL-3.0
    - CC-BY-SA-3.0
summary    : SuperTuxKart is a Free 3D kart racing game, with many tracks, characters and items for you to try
patterns   :
    - assets: /usr/share/supertuxkart
rundeps    :
    - supertuxkart-assets
description: |
    SuperTuxKart is a Free 3D kart racing game, with many tracks, characters and items for you to try
builddeps  :
    - cmake
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(xxf86vm)
    - pkgconfig(fribidi)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - pkgconfig(bluez)
    - libjpeg-turbo-devel
setup      : |
    mkdir build && pushd build
    %cmake ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
