name       : supertuxkart
version    : 0.9.3
release    : 6
source     :
    - https://netix.dl.sourceforge.net/project/supertuxkart/SuperTuxKart/0.9.3/supertuxkart-0.9.3-src.tar.xz : d8014e7106ba84f98b5ec5f146249dcffc284fc4083f8f237ff420b9e2219cb0
license    :
    - GPL-3.0-or-later
    - CC-BY-SA-3.0
component  : games.arcade
summary    : SuperTuxKart is a Free 3D kart racing game, with many tracks, characters
    and items for you to try
description: |
    SuperTuxKart is a 3D open-source arcade racer with a variety characters, tracks, and modes to play.
patterns   :
    - assets : /usr/share/supertuxkart
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(glu)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - pkgconfig(xrandr)
    - libopenglrecorder-devel
    - cantarell-fonts
rundeps    :
    - cantarell-fonts
    - supertuxkart-assets
setup      : |
    %patch -p1 < $pkgfiles/glew.patch
    mkdir build && pushd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build

    rm $installdir/usr/share/supertuxkart/data/ttf/Cantarell-Regular.otf
    ln -s /usr/share/fonts/cantarell/Cantarell-Regular.otf $installdir/usr/share/supertuxkart/data/ttf/Cantarell-Regular.otf
