name       : supertuxkart
version    : '1.3'
release    : 15
source     :
    - https://iweb.dl.sourceforge.net/project/supertuxkart/SuperTuxKart/1.3/SuperTuxKart-1.3-src.tar.xz : eeabeb0d9801688a218f6f0a76ea3546a46a322ccaca9a258148ecacfe083ffd
homepage   : https://supertuxkart.net/
license    :
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
component  :
    - games.arcade
    - assets : games.arcade
summary    : SuperTuxKart is a Free 3D kart racing game, with many tracks, characters and items for you to try
description: |
    SuperTuxKart is a 3D open-source arcade racer with a variety characters, tracks, and modes to play.
patterns   :
    - assets : /usr/share/supertuxkart
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - pkgconfig(xrandr)
    - libopenglrecorder-devel
    - wiiuse-devel
    - cantarell-fonts
rundeps    :
    - cantarell-fonts
    - supertuxkart-assets
setup      : |
    %cmake_ninja -DUSE_SYSTEM_WIIUSE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    rm $installdir/usr/share/supertuxkart/data/ttf/Cantarell-Regular.otf
    ln -s /usr/share/fonts/opentype/cantarell/Cantarell-Regular.otf $installdir/usr/share/supertuxkart/data/ttf/Cantarell-Regular.otf
