name       : supertuxkart
version    : 0.9.2
release    : 2
source     :
    - http://netix.dl.sourceforge.net/project/supertuxkart/SuperTuxKart/0.9.2/supertuxkart-0.9.2-src.tar.xz : 0b080bb098a26adb552d6fd48905bcb6b1e873ef1567457d7268d7d3aaa48282
license    :
    - GPL-3.0
    - CC-BY-SA-3.0
component  : games.arcade
summary    : SuperTuxKart is a Free 3D kart racing game, with many tracks, characters and items for you to try
description: |
    SuperTuxKart is a Free 3D kart racing game, with many tracks, characters and items for you to try
patterns   :
    - assets : /usr/share/supertuxkart
builddeps  :
    - cmake
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(xxf86vm)
    - pkgconfig(fribidi)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - pkgconfig(bluez)
    - libjpeg-turbo-devel
rundeps    :
    - supertuxkart-assets
setup      : |
    mkdir build && pushd build
    %cmake ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
